### ISSUE TITLE
Better default VM configuration 

### ISSUE THREAD

**Issue by tsloughter** [gigalixir/gigalixir-getting-started#15]
My understanding is gigalixir runs on Kubernetes, running user's Elixir releases as pods. 

If that is the case and this, https://github.com/gigalixir/gigalixir-getting-started/blob/js/distillery-2.0/rel/vm.args, is the suggested `vm.args` there are a number of changes you should make. I only tried a `find` on the readthedocs and couldn't find any reference to this stuff, sorry if I simply missed it.

Until OTP 23 Erlang is not cgroup aware and will not take into consideration the cgroup limits placed on it when starting up the VM.

The two most important arguments are one for how quickly a scheduler goes to sleep and how many active schedulers are run.

Basically add theses to the `vm.args`:

```
+sbwt none

+S ${SCHEDULERS}
```

Why to set `sbwt` to `none` I have in here https://adoptingerlang.org/docs/production/kubernetes/#container-resources

Where `SCHEDULERS` is an environment variable set for the container in the pod.

I assume you generate a Pod spec for the projects so could just add to the Pod spec:

```
- name: SCHEDULERS
  valueFrom:
    resourceFieldRef:
      containerName: service-discovery
      resource: limits.cpu
      divisor: 1
```
